services:
  neo4j:
    image: neo4j:5
    ports: ["7474:7474", "7687:7687"]
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
    volumes:
      - neo4jdata:/data
      - ./neo4j/import:/var/lib/neo4j/import

  ollama:
    image: ollama/ollama:latest
    ports: ["11434:11434"]
    volumes:
      - ollamadata:/root/.ollama
    dns: ["8.8.8.8","1.1.1.1"]

  api:
    build: ../app
    env_file:
      - ../app/.env
    depends_on: [neo4j, ollama]
    ports: ["8000:8000"]

  frontend:
    build: ../frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  neo4jdata:
  ollamadata:
